### ISSUE TITLE
Substituir senãose por ouse|ouentão

### ISSUE THREAD

**Issue by alysson-azevedo** [potigol/Potigol#3]
Certa vez participei de uma discussão sobre montar uma versão do python em português, e dei justamente essa contribuição.

segue o link para [possível referência](https://groups.google.com/forum/#!topic/python-brasil/wt-kSVsvlkM)

**Comment by lrlucena** [comment]
Obrigado pela sugestão. Eu concordo que "senãose" não é a solução ideal, mas das alternativas que avaliamos na época da definição da sintaxe foi a menos ruim. Talvez "ouse" seja uma opção melhor. Nós vamos fazer algumas experiências com usuários para avaliar as alternativas de sintaxe. Com certeza vamos analisar as suas sugestões. Obrigado.
