### ISSUE TITLE
Passo implícito de `para` não incrementa variável, segundo `para` não executa

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [potigol/potigol#61]
Teste:

```
var j := 1
para i de j até 10 faça
  escreva j
fim

j := 20
para i de j até 10 faça
  escreva j
fim
```

Resultado:

```
1
1
1
1
1
1
1
1
1
1
```

Esperado:

```
1
2
3
4
5
6
7
8
9
10
20
19
18
17
16
15
14
13
12
11
10
```

**Comment by lrlucena** [comment]
Olá @leonelsanchesdasilva, obrigado por criar a issue.

No primeiro `para`, o resultado gerado está de acordo com o propósito do `para`. A terceira linha do seu código não seria `escreva i`?

```portugol
var j := 1
para i de j até 10 faça
  escreva i
fim
```

No projeto do `para` nós avaliamos implementar o comportamento que você esperava para o segundo `para`. No entanto, para evitar erros do usuário, optamos para que a sequência fosse, por padrão, sempre crescente (passo == 1). Para sequências decrescentes, o passo (-1) teria que aparecer explicitamente:

```portugol
j := 20
para i de j até 10 passo -1 faça
  escreva i
fim
```

Para o passo padrão, o `para` não executa, já que o valor inicial é maior do que o valor final:

```
para i de 20 até 10 faça
  escreva "Esta linha não será executada."
fim
```

**Comment by leonelsanchesdasilva** [comment]
Oi, professor. Obrigado pela resposta.

Isso resolve minha dúvida. Acho que podemos fechar essa issue.
